import type { Metadata } from "next";
import "../styles/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Navigation from "@/components/navigation";
import { Layout } from "antd";
import { Header } from "antd/es/layout/layout";
import UserLogin from "@/components/midm/UserLogin";

export const metadata: Metadata = {
  title: "Mi:dm Playground",
  description: "Generated by KT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <Layout
            style={{ height: "100vh", display: "flex", flexDirection: "row" }}
          >
            <Navigation></Navigation>
            <Layout style={{ height: "100vh" }}>
              <Header
                style={{
                  padding: "0 16px",
                  background: "white",
                  display: "flex",
                  justifyContent: "flex-end",
                }}
              >
                <UserLogin />
              </Header>
              {children}
            </Layout>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
